// Copyright 2023, Evan Palmer
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

#pragma once

#include <Eigen/Dense>

#include "controller_interface/controller_interface.hpp"
#include "geometry_msgs/msg/accel.hpp"
#include "geometry_msgs/msg/twist.hpp"
#include "geometry_msgs/msg/twist_stamped.hpp"
#include "geometry_msgs/msg/wrench_stamped.hpp"
#include "rclcpp/rclcpp.hpp"

// auto-generated by generate_parameter_library
// #include "integral_sliding_mode_controller_parameters.hpp"

namespace velocity_controllers
{

class IntegralSlidingModeController : public controller_interface::ControllerInterface
{
  using Twist = geometry_msgs::msg::Twist;
  using TwistStamped = geometry_msgs::msg::TwistStamped;
  using Accel = geometry_msgs::msg::Accel;
  using WrenchStamped = geometry_msgs::msg::WrenchStamped;
  using Matrix6d = Eigen::Matrix<double, 6, 6>;
  using Vector6d = Eigen::Matrix<double, 6, 1>;

public:
  INTEGRAL_SLIDING_MODE_CONTROLLER_PUBLIC
  IntegralSlidingModeController();

  INTEGRAL_SLIDING_MODE_CONTROLLER_PUBLIC
  controller_interface::InterfaceConfiguration command_interface_configuration() const override;

  INTEGRAL_SLIDING_MODE_CONTROLLER_PUBLIC
  controller_interface::InterfaceConfiguration state_interface_configuration() const override;

  INTEGRAL_SLIDING_MODE_CONTROLLER_PUBLIC
  controller_interface::return_type update(const rclcpp::Time & time,
                                           const rclcpp::Duration & period) override;

  INTEGRAL_SLIDING_MODE_CONTROLLER_PUBLIC
  controller_interface::CallbackReturn on_init() override;

  INTEGRAL_SLIDING_MODE_CONTROLLER_PUBLIC
  controller_interface::CallbackReturn on_configure(
    const rclcpp_lifecycle::State & previous_state) override;

  INTEGRAL_SLIDING_MODE_CONTROLLER_PUBLIC
  controller_interface::CallbackReturn on_activate(
    const rclcpp_lifecycle::State & previous_state) override;

  INTEGRAL_SLIDING_MODE_CONTROLLER_PUBLIC
  controller_interface::CallbackReturn on_deactivate(
    const rclcpp_lifecycle::State & previous_state) override;

  INTEGRAL_SLIDING_MODE_CONTROLLER_PUBLIC
  controller_interface::CallbackReturn on_cleanup(
    const rclcpp_lifecycle::State & previous_state) override;

  INTEGRAL_SLIDING_MODE_CONTROLLER_PUBLIC
  controller_interface::CallbackReturn on_error(
    const rclcpp_lifecycle::State & previous_state) override;

  INTEGRAL_SLIDING_MODE_CONTROLLER_PUBLIC
  controller_interface::CallbackReturn on_shutdown(
    const rclcpp_lifecycle::State & previous_state) override;

protected:
  std::vector<std::string> joint_names_;  // Names of the joints

  Matrix6d p_gain_;            // Proportional gain
  double sliding_gain_;        // Sliding gain
  double boundary_thickness_;  // Manifold boundary thickness

  Vector6d init_vel_error_;  // Initial velocity error
  Vector6d vel_error_;       // Velocity error
  Vector6d accel_error_;     // Acceleration error

  Vector6d cmd_;  // Command to send

  bool subscriber_is_active_ = false;
  rclcpp::Subscription<TwistStamped>::SharedPtr twist_command_subscriber_ = nullptr;
  rclcpp::Subscription<Twist>::SharedPtr twist_unstamped_command_subscriber_ = nullptr;
  realtime_tools::RealtimeBox<std::shared_ptr<TwistStamped>> received_velocity_msg_ptr_{nullptr};

  // ROS parameter interface
  std::shared_ptr<ParamListener> param_listener_;
  Params params_;
};

}  // namespace velocity_controllers
