name: Formatting (pre-commit)

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  pre-commit:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install formatters
        run: sudo apt-get install clang-format-14 cppcheck
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: --all-files --hook-stage manual
